# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish my `do-widget` package

on:
  workflow_dispatch
  # release:
  #   types: [created]

jobs:
  # test:
  #   runs-on: ubuntu-latest 
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - run: npm install
  #     - run: npm run test

  publish-npm:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://repo.sending.me/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure npm credentials
        env:
          # NODE_AUTH_TOKEN: ${{secrets.VERDACCIO_TOKEN}}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        run: |
          echo "email=${NPM_EMAIL}" >> ~/.npmrc
          echo "_auth=$(echo -n "${NPM_USERNAME}:${NPM_PASSWORD}" | base64)" >> ~/.npmrc
      - run: npm publish
        
